print("Welcome to the tip calculator!")
total_bill = float(input("What was the total bill? $ "))
percentage = float(input("How much tip would you like to give? 10, 12, or 15? "))
people_num = int(input("How many people are splitting the bill? "))
pay_per_person = round((total_bill + (total_bill * percentage / 100)) / people_num, 2)
print(f"Each person should pay: ${pay_per_person}")
